version: "3.8"

services:
  api-run:
    container_name: sell-api-run
    build:
      context: ./ 
    image: sec-microservice-rh-api-run
    ports:
    - 9081:80
    # command: tail -f /dev/null 
    environment:
      DB_NAME: ${DB_NAME:-testdb}
      DB_USER: ${DB_USER:-user}
      DB_HOST: ${DB_HOST:-postgres-test}
      DB_PASSWORD: ${DB_PASSWORD:-password}
      API_ENV: ${API_ENV:-test}
      JWT_ACCESS_EXPIRE_MINUTES: ${JWT_ACCESS_EXPIRE_MINUTES:-30} 
      JWT_REFRESH_EXPIRE_MINUTES: ${JWT_REFRESH_EXPIRE_MINUTES:-2880}
      JWT_ALGORITHM: ${JWT_ALGORITHM:-RS256}

      JWT_SECRET_DECODE_KEY: |
        -----BEGIN PUBLIC KEY-----
        MIICIjANBgkqhkiG9w0BAQEFAAOCAg8AMIICCgKCAgEAs2+0WgGnPr2DM+nbUSCF
        jkl5K7ALIE9uGIgUuy+iX3NdeCgeZFy9YeCWwfv1JXN84EL1ddTrS/99uWQZ6VI2
        Mqedc+9oMuboW5BwwqdQp12zyPr9TahnX2T8eHqw+2k+gi6hGzmpV1psb2mAXiFj
        SZ4W6WY+kSxGUBRDZ61Fi9QtTKNMj61xUqZT+LYtSLkbAgIPsk9DeZgHzg2H63zP
        a/YgQbdgfjt+XvJ3vjG648fr+8BZkipEQ/GxTWCtnDn5toBMdIfFfHeu7P0gfz7O
        cn30rP2KYjH8Ku6+WTJmKwZvXtx0OpCvObsIVpaofgEAguXZAMi8irZ6LLLrVGvg
        G3E2TELATxu2h5xt6vhuMxrwXDJ5VhqlMA8OCTyDgd/Wp6o11BNBxRPSvcQmufFy
        T5fTJQ+EDOsVu/qKZnGsp1w+dfBzKL2r5Q9E4Lefc+5Z2b+hAUpzVMcBumLfZHts
        wK9O/OSq6k5AALfv9sPmoKNUSWs5+c+kKh2QSU3SvF8oHC1ZWVll61qXix+WSD4X
        aobYr42itwTEY6fWCjxAzT0Vdy2SuEyeT0CmD3w28TKLJrKIM8ARDSmwxD6O1w/G
        rZe6UAMQWjohfzk1z9vf5YZJHiHy36XaNtJuKTt8YfFFdRsoKoPB/jzDIT6Z9Ltw
        +1I9zcTbXkL2BSR15oy4zc8CAwEAAQ==
        -----END PUBLIC KEY-----

      JWT_SECRET_ENCODE_KEY: |
        -----BEGIN PRIVATE KEY-----
        MIIJQgIBADANBgkqhkiG9w0BAQEFAASCCSwwggkoAgEAAoICAQCzb7RaAac+vYMz
        6dtRIIWOSXkrsAsgT24YiBS7L6Jfc114KB5kXL1h4JbB+/Ulc3zgQvV11OtL/325
        ZBnpUjYyp51z72gy5uhbkHDCp1CnXbPI+v1NqGdfZPx4erD7aT6CLqEbOalXWmxv
        aYBeIWNJnhbpZj6RLEZQFENnrUWL1C1Mo0yPrXFSplP4ti1IuRsCAg+yT0N5mAfO
        DYfrfM9r9iBBt2B+O35e8ne+Mbrjx+v7wFmSKkRD8bFNYK2cOfm2gEx0h8V8d67s
        /SB/Ps5yffSs/YpiMfwq7r5ZMmYrBm9e3HQ6kK85uwhWlqh+AQCC5dkAyLyKtnos
        sutUa+AbcTZMQsBPG7aHnG3q+G4zGvBcMnlWGqUwDw4JPIOB39anqjXUE0HFE9K9
        xCa58XJPl9MlD4QM6xW7+opmcaynXD518HMovavlD0Tgt59z7lnZv6EBSnNUxwG6
        Yt9ke2zAr0785KrqTkAAt+/2w+ago1RJazn5z6QqHZBJTdK8XygcLVlZWWXrWpeL
        H5ZIPhdqhtivjaK3BMRjp9YKPEDNPRV3LZK4TJ5PQKYPfDbxMosmsogzwBENKbDE
        Po7XD8atl7pQAxBaOiF/OTXP29/lhkkeIfLfpdo20m4pO3xh8UV1Gygqg8H+PMMh
        Ppn0u3D7Uj3NxNteQvYFJHXmjLjNzwIDAQABAoICAES0WTx7VJPH0YRfnxulla3B
        ATXSnrf84d1fwXxYxVXB4QCgb96iydq/uUnGVPvFiAOAb+bxozSCu5twMiGt2lWz
        6yxYdy/CTSa+HAbUNKQY0z15qOKCwC39B1SEOd7R0d7bxtEbV3U8iLdyEHY6V395
        GjG89ej1KGkCETsR08ax87Rb9HUxBmqMiCt7acRmJ+qxalwuUFou9ZIWiTwIGo2u
        fHRdKAO9eOoW8fVvqi0MQBWxdTprl57iXK6RfXgLlMslveCCmgHJ+77/PuGp5Tde
        dgCExedKV1EC//w8OXVw7dTHGXPRMV6r+AnbfuFcNdto8ZmEwvhj3UzfJw84jOKg
        DImM4Hl0cqkYfNth+3n/pglA3MW6Gm+6VfYawCxRQsS4xOQtO00awJ/xEdDR8rrx
        0rlkuK9iStYE9xeR7bGGCPWALNnwxf4EKrEi9al58ANsg6TF/1q+KTuAn4kzQirh
        3gXlCXSSld+cApOIKBnd3Aumoa5nTg+VKkz/WEKD6rg/SsgBt58NJLaXumhM13WJ
        fupnf3YiHaRo6kFGHuKHPpDARIanslB/nkkIBJNLSYz3IH13zomuaechPSb0XC7C
        bv5Mv8Oqm6JAPAgUIjSLKlnA7lxp7WSLP/IOyRtupK6geXldxgWgTnT39V6cTVai
        dffCAQwgda4uQd0orPY1AoIBAQDtfNdMA8TQl19oqEIT7AYxdfrRvELmWxDNM6ma
        dcC7dv8FhDB35HUGHfHNKDPY3AfG8lRBqwx52QkHtcingEFabty5L4no8RCnD9su
        vnlLRN/STjlBVHklUOwd+NgNKJq7x+SGhMQAveF/NvpjhU+xg0mXX6Cm7q3PzirC
        FHdkQ4WoM4HMxO+7vbKq3OGcaysHj5IHl7Uoc6VUDvPuP59Hk4AxSa6QPWak6CEb
        JQj8p2EZyeivWla4+gWZQlgssrhgPbkTuHYAJ7L8JOoA7PIx2SVVuygLsi+ErTtI
        4GHXTic4A6xop7dqtcfE+8RolcE2cvO/gealjJyxFblRlmQtAoIBAQDBbG1Fwn1W
        gC0XrosubriAqffHlUbWSb8Q/UZR8N9R334/ypk0cYOXvB/xxfswrE6yT83tf4KT
        ydvYPQBUQ06kfBC/4OlLAB9vVglrh7lIcuf0yllj3AspbnoN7CVk6ZcS9zX2dDKd
        sLObzRAJxS09EOyKBh0kRs6QY0F8V0c1FPQHtKT1WXcYiS6m5ZrvEQXp0aCSgYQC
        hgrxSZJoBIeBH8MKFeg8XweNHqndl7N6g5dlUkZuPTQl3f2isxaqM4a5dz8db0J7
        jNfyTdNAIhTLD3flAHnNMrsF6EEkMZpm2y4bX8RWg6RvNKOc3KIwlsC6o6DgI+av
        +dlya95tKwtrAoIBAD5rJocjInKUpo3yU1O7IDGVybOgYJD89GCKqJQhSOO8tfB0
        Ouz4Dc3qxufeHipsQlsGzCBqXaAU7Curmq5zpjmnk7nUhdHEslTGdRxHEcg3tQAo
        cSH7ms+1AioqglaLCog6VJUKhh2PypnOEGdh3X1RfWEc0DOv3d0VWeWizXJ70MBR
        sVbpl/znMfN4lI+xFyEomgAG3qVgJ979Ax3meO2uFe5eaFQe30COhk0FIeSN9ZZ6
        m/6iptJ9XEVYy6YL3yvkbSWCwPjvdjqRVTOjE1EIuqhaxX61eYnMoh1YZD7bmrE9
        Pe5PzoRsfLIIXioC2kJ+WhRGhyGR4IkmpYuNFI0CggEBAIoe8j0BcF1ntEuX8X2b
        xRbjyLN1zprRGKZ6Jk/3MJGXheDpvNNtR+n/hdQxa3lLYfsE7+lrx4PffqUAko6Z
        bbwZeCB87DsJgGkRyDJIPjAVFbyBDqo3hKT2ZiQxAFb6U05Qx/EQ8uAWQXu9SHmh
        mvdjcXXyfbbc9T64EhhHfurR5pzmC3HEjD4yH+VASo3y2wUoE4DrCah/raq1vd2X
        dmfnlXBLSoZp2cuVHPnHDXwsId1RjkfEXsu3pRocxs+NceRY2fIb9B6j6cT2fCbs
        72o9xoD6AQBd/J1wR6wf28EdPOSBU4PwB2j97uPhzdPiowfkNso3+NCrGvMRQkk0
        lrcCggEARp6jTCh6tzvyjsUZmmWMaK6mED6XxR6z7adsVUD6ApnBKvy9gwbxmL3n
        S0n67WhwW/5bmllYQciOBWROOE+ktwB4VJFRbWodgMMETBDttcSnSxpdnZJGNcsK
        BqXVXw5SKuG+JxdjrSYVBmEZxQGV1eiNqRxHKKnDB5fCFs1tO9FT3kZyQaLlDl+f
        GUwrCp0yD0TuUDP5PM7o2De58wt5pUONyBT9qNBuZ5ru0Bz2aU2JMLdEdk4KKRhJ
        oNbG3pMI6ngEun1FBCBfXARMZ2oF63RhsH67/wbI7deAohizM+eLtxPskYAsrQus
        7HrmRa7ofO8NFWB0IpDH+WQzineHWA==
        -----END PRIVATE KEY-----

      JWT_REFRESH_SECRET_KEY: ${JWT_REFRESH_SECRET_KEY:-testunsaferefresh}
    networks:
    - sec-microservice-rh_service
    - db
    depends_on:
    - postgres-test
    volumes:
      - ./backend/:/backend/
  api-test:
    container_name: sell-api-test
    build:
      context: ./ 
    # ports:
    # - 9080:80
    command: 'poetry run pytest tests -x -vv --cov=. --cov-report=xml:./code-coverage/coverage.xml'
    # command: tail -f /dev/null 
    volumes:
    - .coverage/:/backend/code-coverage/
    - ./backend/tests/:/backend/tests
    # - ./.venv:/opt/venv/
    networks:
    - sec-microservice-rh_service
    - db
    environment:
      DB_NAME: ${DB_NAME:-testdb}
      DB_USER: ${DB_USER:-user}
      DB_HOST: ${DB_HOST:-postgres-test}
      DB_PASSWORD: ${DB_PASSWORD:-password}
      API_ENV: ${API_ENV:-test}
      JWT_ACCESS_EXPIRE_MINUTES: ${JWT_ACCESS_EXPIRE_MINUTES:-30} 
      JWT_REFRESH_EXPIRE_MINUTES: ${JWT_REFRESH_EXPIRE_MINUTES:-2880}
      JWT_ALGORITHM: ${JWT_ALGORITHM:-RS256}

      JWT_SECRET_DECODE_KEY: |
        -----BEGIN PUBLIC KEY-----
        MIICIjANBgkqhkiG9w0BAQEFAAOCAg8AMIICCgKCAgEAs2+0WgGnPr2DM+nbUSCF
        jkl5K7ALIE9uGIgUuy+iX3NdeCgeZFy9YeCWwfv1JXN84EL1ddTrS/99uWQZ6VI2
        Mqedc+9oMuboW5BwwqdQp12zyPr9TahnX2T8eHqw+2k+gi6hGzmpV1psb2mAXiFj
        SZ4W6WY+kSxGUBRDZ61Fi9QtTKNMj61xUqZT+LYtSLkbAgIPsk9DeZgHzg2H63zP
        a/YgQbdgfjt+XvJ3vjG648fr+8BZkipEQ/GxTWCtnDn5toBMdIfFfHeu7P0gfz7O
        cn30rP2KYjH8Ku6+WTJmKwZvXtx0OpCvObsIVpaofgEAguXZAMi8irZ6LLLrVGvg
        G3E2TELATxu2h5xt6vhuMxrwXDJ5VhqlMA8OCTyDgd/Wp6o11BNBxRPSvcQmufFy
        T5fTJQ+EDOsVu/qKZnGsp1w+dfBzKL2r5Q9E4Lefc+5Z2b+hAUpzVMcBumLfZHts
        wK9O/OSq6k5AALfv9sPmoKNUSWs5+c+kKh2QSU3SvF8oHC1ZWVll61qXix+WSD4X
        aobYr42itwTEY6fWCjxAzT0Vdy2SuEyeT0CmD3w28TKLJrKIM8ARDSmwxD6O1w/G
        rZe6UAMQWjohfzk1z9vf5YZJHiHy36XaNtJuKTt8YfFFdRsoKoPB/jzDIT6Z9Ltw
        +1I9zcTbXkL2BSR15oy4zc8CAwEAAQ==
        -----END PUBLIC KEY-----

      JWT_SECRET_ENCODE_KEY: |
        -----BEGIN PRIVATE KEY-----
        MIIJQgIBADANBgkqhkiG9w0BAQEFAASCCSwwggkoAgEAAoICAQCzb7RaAac+vYMz
        6dtRIIWOSXkrsAsgT24YiBS7L6Jfc114KB5kXL1h4JbB+/Ulc3zgQvV11OtL/325
        ZBnpUjYyp51z72gy5uhbkHDCp1CnXbPI+v1NqGdfZPx4erD7aT6CLqEbOalXWmxv
        aYBeIWNJnhbpZj6RLEZQFENnrUWL1C1Mo0yPrXFSplP4ti1IuRsCAg+yT0N5mAfO
        DYfrfM9r9iBBt2B+O35e8ne+Mbrjx+v7wFmSKkRD8bFNYK2cOfm2gEx0h8V8d67s
        /SB/Ps5yffSs/YpiMfwq7r5ZMmYrBm9e3HQ6kK85uwhWlqh+AQCC5dkAyLyKtnos
        sutUa+AbcTZMQsBPG7aHnG3q+G4zGvBcMnlWGqUwDw4JPIOB39anqjXUE0HFE9K9
        xCa58XJPl9MlD4QM6xW7+opmcaynXD518HMovavlD0Tgt59z7lnZv6EBSnNUxwG6
        Yt9ke2zAr0785KrqTkAAt+/2w+ago1RJazn5z6QqHZBJTdK8XygcLVlZWWXrWpeL
        H5ZIPhdqhtivjaK3BMRjp9YKPEDNPRV3LZK4TJ5PQKYPfDbxMosmsogzwBENKbDE
        Po7XD8atl7pQAxBaOiF/OTXP29/lhkkeIfLfpdo20m4pO3xh8UV1Gygqg8H+PMMh
        Ppn0u3D7Uj3NxNteQvYFJHXmjLjNzwIDAQABAoICAES0WTx7VJPH0YRfnxulla3B
        ATXSnrf84d1fwXxYxVXB4QCgb96iydq/uUnGVPvFiAOAb+bxozSCu5twMiGt2lWz
        6yxYdy/CTSa+HAbUNKQY0z15qOKCwC39B1SEOd7R0d7bxtEbV3U8iLdyEHY6V395
        GjG89ej1KGkCETsR08ax87Rb9HUxBmqMiCt7acRmJ+qxalwuUFou9ZIWiTwIGo2u
        fHRdKAO9eOoW8fVvqi0MQBWxdTprl57iXK6RfXgLlMslveCCmgHJ+77/PuGp5Tde
        dgCExedKV1EC//w8OXVw7dTHGXPRMV6r+AnbfuFcNdto8ZmEwvhj3UzfJw84jOKg
        DImM4Hl0cqkYfNth+3n/pglA3MW6Gm+6VfYawCxRQsS4xOQtO00awJ/xEdDR8rrx
        0rlkuK9iStYE9xeR7bGGCPWALNnwxf4EKrEi9al58ANsg6TF/1q+KTuAn4kzQirh
        3gXlCXSSld+cApOIKBnd3Aumoa5nTg+VKkz/WEKD6rg/SsgBt58NJLaXumhM13WJ
        fupnf3YiHaRo6kFGHuKHPpDARIanslB/nkkIBJNLSYz3IH13zomuaechPSb0XC7C
        bv5Mv8Oqm6JAPAgUIjSLKlnA7lxp7WSLP/IOyRtupK6geXldxgWgTnT39V6cTVai
        dffCAQwgda4uQd0orPY1AoIBAQDtfNdMA8TQl19oqEIT7AYxdfrRvELmWxDNM6ma
        dcC7dv8FhDB35HUGHfHNKDPY3AfG8lRBqwx52QkHtcingEFabty5L4no8RCnD9su
        vnlLRN/STjlBVHklUOwd+NgNKJq7x+SGhMQAveF/NvpjhU+xg0mXX6Cm7q3PzirC
        FHdkQ4WoM4HMxO+7vbKq3OGcaysHj5IHl7Uoc6VUDvPuP59Hk4AxSa6QPWak6CEb
        JQj8p2EZyeivWla4+gWZQlgssrhgPbkTuHYAJ7L8JOoA7PIx2SVVuygLsi+ErTtI
        4GHXTic4A6xop7dqtcfE+8RolcE2cvO/gealjJyxFblRlmQtAoIBAQDBbG1Fwn1W
        gC0XrosubriAqffHlUbWSb8Q/UZR8N9R334/ypk0cYOXvB/xxfswrE6yT83tf4KT
        ydvYPQBUQ06kfBC/4OlLAB9vVglrh7lIcuf0yllj3AspbnoN7CVk6ZcS9zX2dDKd
        sLObzRAJxS09EOyKBh0kRs6QY0F8V0c1FPQHtKT1WXcYiS6m5ZrvEQXp0aCSgYQC
        hgrxSZJoBIeBH8MKFeg8XweNHqndl7N6g5dlUkZuPTQl3f2isxaqM4a5dz8db0J7
        jNfyTdNAIhTLD3flAHnNMrsF6EEkMZpm2y4bX8RWg6RvNKOc3KIwlsC6o6DgI+av
        +dlya95tKwtrAoIBAD5rJocjInKUpo3yU1O7IDGVybOgYJD89GCKqJQhSOO8tfB0
        Ouz4Dc3qxufeHipsQlsGzCBqXaAU7Curmq5zpjmnk7nUhdHEslTGdRxHEcg3tQAo
        cSH7ms+1AioqglaLCog6VJUKhh2PypnOEGdh3X1RfWEc0DOv3d0VWeWizXJ70MBR
        sVbpl/znMfN4lI+xFyEomgAG3qVgJ979Ax3meO2uFe5eaFQe30COhk0FIeSN9ZZ6
        m/6iptJ9XEVYy6YL3yvkbSWCwPjvdjqRVTOjE1EIuqhaxX61eYnMoh1YZD7bmrE9
        Pe5PzoRsfLIIXioC2kJ+WhRGhyGR4IkmpYuNFI0CggEBAIoe8j0BcF1ntEuX8X2b
        xRbjyLN1zprRGKZ6Jk/3MJGXheDpvNNtR+n/hdQxa3lLYfsE7+lrx4PffqUAko6Z
        bbwZeCB87DsJgGkRyDJIPjAVFbyBDqo3hKT2ZiQxAFb6U05Qx/EQ8uAWQXu9SHmh
        mvdjcXXyfbbc9T64EhhHfurR5pzmC3HEjD4yH+VASo3y2wUoE4DrCah/raq1vd2X
        dmfnlXBLSoZp2cuVHPnHDXwsId1RjkfEXsu3pRocxs+NceRY2fIb9B6j6cT2fCbs
        72o9xoD6AQBd/J1wR6wf28EdPOSBU4PwB2j97uPhzdPiowfkNso3+NCrGvMRQkk0
        lrcCggEARp6jTCh6tzvyjsUZmmWMaK6mED6XxR6z7adsVUD6ApnBKvy9gwbxmL3n
        S0n67WhwW/5bmllYQciOBWROOE+ktwB4VJFRbWodgMMETBDttcSnSxpdnZJGNcsK
        BqXVXw5SKuG+JxdjrSYVBmEZxQGV1eiNqRxHKKnDB5fCFs1tO9FT3kZyQaLlDl+f
        GUwrCp0yD0TuUDP5PM7o2De58wt5pUONyBT9qNBuZ5ru0Bz2aU2JMLdEdk4KKRhJ
        oNbG3pMI6ngEun1FBCBfXARMZ2oF63RhsH67/wbI7deAohizM+eLtxPskYAsrQus
        7HrmRa7ofO8NFWB0IpDH+WQzineHWA==
        -----END PRIVATE KEY-----

      JWT_REFRESH_SECRET_KEY: ${JWT_REFRESH_SECRET_KEY:-testunsaferefresh}
    depends_on:
    - postgres-test
  postgres-test:
    container_name: sell-postgres-test
    image: postgres:16-alpine
    # volumes:
    # - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${DB_NAME:-testdb}
      POSTGRES_USER: ${DB_USER:-user}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-password}

    # ports:
    # - 5432:5432

    networks:
    - db 
  # my-rabbit:
  #   container_name: rabbit-broker
  #   image: rabbitmq:3-management

  #   ports:
  #   - 9180:15672 
  #   - 5672:5672
  #   - 25676:25676

  #   networks:
  #   - service

# volumes:
  # pgdata:
networks:
  sec-microservice-rh_service:
    external: true
  db:
