apiVersion: apps/v1
kind: Deployment
metadata:
  name: sellservice-dev
  namespace: tcc
spec:
  selector:
    matchLabels:
      app: sellservice-dev
  replicas: 1
  template:
    metadata:
      labels:
        app: sellservice-dev
    spec:
      initContainers:
      - name: init-postgres
        image: busybox
        command:
          - 'sh'
          - '-c'
          - |
            until nslookup postgres-service-rh-dev.tcc.svc.cluster.local; do \
            echo waiting for Postgres; sleep 2; \
            done
        env:
        - name: DB_HOST
          valueFrom:
            secretKeyRef:
              name: tcc-micro-secret
              key: PT_DB_HOST
      containers:
      - name: sec-microservice-sells
        image: swamptg/sec-microservice-sells:latest
        imagePullPolicy: Always
        command: ["poetry", "run", "uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "80", "--reload"]
        envFrom:
        - secretRef:
            name: tcc-micro-secret
        env:
        - name: BROKER_HOST
          valueFrom:
            secretKeyRef:
              name:  rabbit-exchange-secret
              key: BROKER_HOST
        - name: BROKER_PASS
          valueFrom:
            secretKeyRef:
              name:  rabbit-exchange-secret
              key: BROKER_PASS
        - name: BROKER_PORT
          valueFrom:
            secretKeyRef:
              name:  rabbit-exchange-secret
              key: BROKER_PORT
        - name: BROKER_USER
          valueFrom:
            secretKeyRef:
              name:  rabbit-exchange-secret
              key: BROKER_USER
        - name: DB_NAME
          valueFrom:
            secretKeyRef:
              name: tcc-micro-secret
              key: PT_DB_NAME
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: tcc-micro-secret
              key: PT_DB_USER
        - name: DB_HOST
          valueFrom:
            secretKeyRef:
              name: tcc-micro-secret
              key: PT_DB_HOST
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: tcc-micro-secret
              key: PT_DB_PASSWORD
        # - name: API_ENV 
        #   value: dev
        ports:
        - name: http-rh
          containerPort: 80
        resources:
          requests:
            cpu: '150m'
            memory: '50Mi'
          limits:
            cpu: '300m'
            memory: '300Mi'
        livenessProbe:
          initialDelaySeconds: 120
          periodSeconds: 120
          timeoutSeconds: 120
          failureThreshold: 2
          httpGet:
            host:
            scheme: HTTP
            path: /check/
            httpHeaders:
              - name: Host
                value: localhost
            port: 80
---
apiVersion: v1
kind: Service
metadata:
  namespace: tcc
  name: sellservice-dev
  labels:
    app: sellservice-dev
spec:
  type: ClusterIP
  selector:
    app: sellservice-dev
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
