apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sell-ingress-minion
  namespace: tcc
  annotations:
    nginx.org/mergeable-ingress-type: "minion"
    nginx.ingress.kubernetes.io/backend-protocol: HTTP
    # nginx.ingress.kubernetes.io/rewrite-target: "/$2"
spec:
  ingressClassName: nginx
  rules:
  - host: apisell.adrianlopes-swe.com.br
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: sellservice-dev
            port:
              number: 80
